

service: pylocaltest

plugins:
  - serverless-step-functions
  - serverless-step-functions-local
  - serverless-offline-lambda
  - serverless-offline
  
custom:
  stepFunctionsLocal:
    accountId: 123456789012
    region: us-east-1
    lambdaEndpoint: http://localhost:3002
    TaskResourceMapping:
      FirstState: arn:aws:lambda:us-east-1:123456789012:function:theFirst
      FinalState: arn:aws:lambda:us-east-1:123456789012:function:theSecond

provider:
  name: aws
  runtime: python3.7

stage: dev

functions:
  first:
    handler: handler.hello
    name: theFirst
  second:
    handler: handler.welcome
    name: theSecond

stepFunctions:
  stateMachines:
    foo:
      definition:
        StartAt: FirstState
        States:
          FirstState:
              Type: Task
              Resource: 
                Fn::GetAtt: [first, Arn]
              Next: FinalState
          FinalState:
            Type: Task
            Resource: 
              Fn::GetAtt: [second, Arn]
            End: true
